// AUTO-GENERATED by @nonnajs/compiler - do not edit by hand.
import { defineDependencies } from "@nonnajs/di";
import { LoggerService } from "../services/logger.service";
import { UserRepository } from "../services/user.repository";
import { UserService } from "../services/user.service";
defineDependencies(LoggerService, []);
defineDependencies(UserRepository, []);
defineDependencies(UserService, [
    UserRepository
]);
