/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AddUserForm {
    }
    interface DebugPanel {
    }
    interface GreetingBanner {
    }
    interface UserList {
    }
}
declare global {
    interface HTMLAddUserFormElement extends Components.AddUserForm, HTMLStencilElement {
    }
    var HTMLAddUserFormElement: {
        prototype: HTMLAddUserFormElement;
        new (): HTMLAddUserFormElement;
    };
    interface HTMLDebugPanelElement extends Components.DebugPanel, HTMLStencilElement {
    }
    var HTMLDebugPanelElement: {
        prototype: HTMLDebugPanelElement;
        new (): HTMLDebugPanelElement;
    };
    interface HTMLGreetingBannerElement extends Components.GreetingBanner, HTMLStencilElement {
    }
    var HTMLGreetingBannerElement: {
        prototype: HTMLGreetingBannerElement;
        new (): HTMLGreetingBannerElement;
    };
    interface HTMLUserListElement extends Components.UserList, HTMLStencilElement {
    }
    var HTMLUserListElement: {
        prototype: HTMLUserListElement;
        new (): HTMLUserListElement;
    };
    interface HTMLElementTagNameMap {
        "add-user-form": HTMLAddUserFormElement;
        "debug-panel": HTMLDebugPanelElement;
        "greeting-banner": HTMLGreetingBannerElement;
        "user-list": HTMLUserListElement;
    }
}
declare namespace LocalJSX {
    interface AddUserForm {
    }
    interface DebugPanel {
    }
    interface GreetingBanner {
    }
    interface UserList {
    }
    interface IntrinsicElements {
        "add-user-form": AddUserForm;
        "debug-panel": DebugPanel;
        "greeting-banner": GreetingBanner;
        "user-list": UserList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-user-form": LocalJSX.IntrinsicElements["add-user-form"] & JSXBase.HTMLAttributes<HTMLAddUserFormElement>;
            "debug-panel": LocalJSX.IntrinsicElements["debug-panel"] & JSXBase.HTMLAttributes<HTMLDebugPanelElement>;
            "greeting-banner": LocalJSX.IntrinsicElements["greeting-banner"] & JSXBase.HTMLAttributes<HTMLGreetingBannerElement>;
            "user-list": LocalJSX.IntrinsicElements["user-list"] & JSXBase.HTMLAttributes<HTMLUserListElement>;
        }
    }
}
